### ISSUE TITLE
ImportError: No module named gasol

### ISSUE THREAD

**Issue by 1uvu** [costa-group/EthIR#1]
hello, when i test your program, i meet following error, request help~
> python oyente-ethir.py -s test/test
> Traceback (most recent call last):
>   File "oyente-ethir.py", line 7, in <module>
>     import symExec
>   File "/usr/bin/EthIR-master/ethir/symExec.py", line 18, in <module>
>     import gasol
> ImportError: No module named gasol

my os is ubuntu18.04, python2.
waitting for your reply!

**Comment by tutugordillo** [comment]
It should be solved.
If you execute 
`python oyente-ethir.py -s ../examples/loop1.sol`
 it should work.

**Comment by 1uvu** [comment]
thanks！:>
