### ISSUE TITLE
some error when build error

### ISSUE THREAD

**Issue by ouerum** [costa-group/EthIR#1]
Hi, I try to use your tool to build Control Graph with EtherDelta contract just with bytecode, but the result of cfg is not completed, the function ` full_sym_exec()` in `symExec.py` not work well. 

you can find the bytecode in https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819,
And here is my output file:
[rbr.txt](https://github.com/costa-group/EthIR/files/2946075/rbr.txt)

I think it is not the complete CFG of this contract, it's block is too little. Please help, thanks!

**Comment by ouerum** [comment]
sorry, the output file is form /examples/advertisement.sol in you project. And EtherDelta can not run this program.

**Comment by ouerum** [comment]
also the example in /examples/sums.sol did not work in your project

**Comment by tutugordillo** [comment]
Hi, 
what dou you mean with "did not work in your project"? Did you get an exception message?
Which command did you execute? I have run the three solidity examples that you mention and the execution finishes without error.

**Comment by ouerum** [comment]
there is no exception msg show for me. I use 'python2 oyente-ethir.py -s xxx.sol' or  'python2 oyente-ethir.py -s xxx.evm -b'  to build cfg. Aslo, I try to use python3, but show syntax error.

And I have installed solc, evm, z3 in the way showed in readme. 

I did not know what error occurred, so I try to connect you. thinks for your reply.

p.s. I run it in Mac, not Ubuntu :)

**Comment by tutugordillo** [comment]
If you don't get an exception message it executes correctly. I run it with python 2.7 using the follwoing command:
./oyente-ethir.py -s xxx.sol -cfg
It will generate a .cfg file and a .dot file for each contract that appears in the solidity file. These cfg files contain the cfg of each contract in text mode and as a dot image respectively. Note that each contract of the solidity file is executed independently so EthIR generates one file for each contract. For example, if you run EthIR with the contract that you mention in the first post, it will generate 7 cfg files, 7 dot files, 7 rbr files...one for each contract.

Which versions of solc and evm are you using? They should be solc v0.4.25 and evm v1.8.18

**Comment by ouerum** [comment]
Thanks. I have try it in Ubuntu and it run correctly but not in osX. It show Exception: 1 when i use command:
python2 ./oyente-ethir.py -s xxx.sol -cfg 
When I use Pycharm to debug the detail of this exception, the detail of exception is:
'NoneType' object has no attribute 'get_start_address'

In ubuntu, solc: 0.4.25, evm: 1.8.18. In osX, solc: 0.4.25, evm: 1.8.14-stable

**Comment by tutugordillo** [comment]
We haven't tested it for osX yet. Can you send me a link to the sol file that you are using to check it?
