### ISSUE TITLE
How to run GASTAP？

### ISSUE THREAD

**Issue by BigGan** [costa-group/EthIR#2]
Hello, I've read your paper about GASTAP, I think it is great. But I don't know how to use this source code to run GASTAP. I confuse that how the SACO inffer the loop bound. Thanks for your great job!

**Comment by tutugordillo** [comment]
Hi!
The code of this repo only covers the part of EthIR, our decompiler. It generates the intermediate representation used by GASTAP tp infer the gas upper-bounds. The other component of GASTAP (the solver) is not open-source but the tool can be used online in the following link: https://costa.fdi.ucm.es/gastap/

It is under maintenance until next week. To use it you have to write or load your smart contract in the text editor area (the central one) and click on Refresh Outline. It loads all the public functions of the contract on your right hand (if not, the contract has a compiler error). Then, you have to select the public function that you want to analyze and click on Apply. The upper-bound will appear in the console area (at the bottom of the page)

If you are interested in the way the bounds are computed you can take a look to the follwoing papers:
http://costa.fdi.ucm.es/papers/costa/AlbertAGP10.pdf
http://costa.fdi.ucm.es/papers/costa/AlbertAFGGMPR14.pdf

Thanks for your interest :-)

**Comment by BigGan** [comment]
> Hi!
> The code of this repo only covers the part of EthIR, our decompiler. It generates the intermediate representation used by GASTAP tp infer the gas upper-bounds. The other component of GASTAP (the solver) is not open-source but the tool can be used online in the following link: https://costa.fdi.ucm.es/gastap/
> 
> It is under maintenance until next week. To use it you have to write or load your smart contract in the text editor area (the central one) and click on Refresh Outline. It loads all the public functions of the contract on your right hand (if not, the contract has a compiler error). Then, you have to select the public function that you want to analyze and click on Apply. The upper-bound will appear in the console area (at the bottom of the page)
> 
> If you are interested in the way the bounds are computed you can take a look to the follwoing papers:
> http://costa.fdi.ucm.es/papers/costa/AlbertAGP10.pdf
> http://costa.fdi.ucm.es/papers/costa/AlbertAFGGMPR14.pdf
> 
> Thanks for your interest :-)

Thank you for your reply. I will read the paper.
