### ISSUE TITLE
Can I use older solc version?

### ISSUE THREAD

**Issue by Xcrab** [costa-group/EthIR#3]
This tool can use solc 0.4.25, but if I use anthor version like 0.4.24, it can't work. So, Is it only can use solc 0.4.25?

**Comment by tutugordillo** [comment]
I have just check it and  the tool works for v.0.4.24 (https://github.com/ethereum/solidity/releases/tag/v0.4.24). Note that the error can be thrown just for a specific example where the decomplitaion phase fails.

**Comment by Xcrab** [comment]
608060405234801561001057600080fd5b5033600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555061047f806100616000396000f30060806040526004361061006d576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063110ba0f9146100725780638da5cb5b146100db578063b863bd3714610132578063c8eab53714610173578063e72f5f63146101c4575b600080fd5b34801561007e57600080fd5b506100a3600480360381019080803563ffffffff1690602001909291905050506101ef565b604051808463ffffffff1663ffffffff1681526020018360001916600019168152602001828152602001935050505060405180910390f35b3480156100e757600080fd5b506100f0610229565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561013e57600080fd5b5061015d6004803603810190808035906020019092919050505061024f565b6040518082815260200191505060405180910390f35b34801561017f57600080fd5b506101c2600480360381019080803563ffffffff1690602001909291908035600019169060200190929190803563ffffffff16906020019092919050505061026b565b005b3480156101d057600080fd5b506101d96103c9565b6040518082815260200191505060405180910390f35b60016020528060005260406000206000915090508060000160009054906101000a900463ffffffff16908060010154908060020154905083565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60008161025a6103c9565b81151561026357fe5b069050919050565b6000600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156102c957600080fd5b60008263ffffffff161115156102de57600080fd5b6102ed8263ffffffff1661024f565b90506060604051908101604052808363ffffffff1681526020018460001916815260200182815250600160008663ffffffff1663ffffffff16815260200190815260200160002060008201518160000160006101000a81548163ffffffff021916908363ffffffff16021790555060208201518160010190600019169055604082015181600201559050507f97f6735001b531af63662eaadac3df47a2bb56bb7079ffcfd56f5875f6e4cfee8482604051808363ffffffff1663ffffffff1681526020018281526020019250505060405180910390a150505050565b60008054600143034041446040518085815260200184600019166000191681526020018373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166c010000000000000000000000000281526014018281526020019450505050506040518091039020600190046000819055506000549050905600a165627a7a72305820dd54e1f7ad8351e3cda97ed8e166399aaf9045dea469cbeadc0986cbbd45fcc50029

You can try to use this bin  to generate the CFG, It will throw error.

I use this command : `python ethir/oyente-ethir.py -s examples/Lottery.evm -b -cfg`

![Screenshot from 2019-07-16 21-44-14](https://user-images.githubusercontent.com/20314873/61299616-026c2e80-a813-11e9-8a76-dc2a9f1556c1.png)

I try to fix this BUG:
'dot_tree.py' at row 54 and row 69, I add some code

![webwxgetmsgimg](https://user-images.githubusercontent.com/20314873/61300407-7b1fba80-a814-11e9-936a-39b8cd09b796.jpg)

Can I do this? Or you have a better method to fix it?

**Comment by tutugordillo** [comment]
Does it comes from a solidity file? 
The cfg is generated in text mode in the directory /tmp/costabs/ . What is failing is the generation of the graphic mode. The problem is not from the tool indeed. It fails because the evm that it receives is "strange". It makes a jump to an invalid instruction according to the disassembly code generated by the Ethereum Virtual Machine. It tries to jump to the address 0x6d but this address is not a possible jump destination one (it should be 0x6e according to the code generated by the virtual machine) so it doesn't correspond to any block generated. EthIR works under the assumption that all the inputs are correct in that sense.

**Comment by Xcrab** [comment]
I'm sure that it comes from a solidity file!!
My solc version is '0.4.25+commit.59dbf8f1.Linux.g++'
![Screenshot from 2019-07-17 12-39-39](https://user-images.githubusercontent.com/20314873/61347551-fc686300-a88f-11e9-9c46-0cb1b24de18b.png)

And my command is 
'solc --bin -o ./ factorial.sol'
![Screenshot from 2019-07-17 12-48-54](https://user-images.githubusercontent.com/20314873/61347929-59184d80-a891-11e9-8d21-90c99a597d2a.png)
'python ethir/oyente-ethir.py -s examples/Factorial.bin -b -cfg'
![Screenshot from 2019-07-17 12-49-26](https://user-images.githubusercontent.com/20314873/61348000-95e44480-a891-11e9-8d74-459a4ebbeb66.png)

**Comment by tutugordillo** [comment]
oooh! That may be the problem. It is not able to analyze recursive functions. Anyway, can you send me the sol file? pabgordi@ucm.es

**Comment by Xcrab** [comment]
Of course, I just sent it to you.
